//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("symbolspace")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Release")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("© symbolspace All rights reserved.")]
[assembly: System.Reflection.AssemblyDescriptionAttribute("symbolspace .net library")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("4.0.0.1")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("4.0.0.1")]
[assembly: System.Reflection.AssemblyProductAttribute("Symbol.Data")]
[assembly: System.Reflection.AssemblyTitleAttribute("Symbol.Data")]
[assembly: System.Reflection.AssemblyVersionAttribute("4.0.0.1")]
[assembly: System.Resources.NeutralResourcesLanguageAttribute("zh-CN")]

// 由 MSBuild WriteCodeFragment 类生成。

